# Generated by Django 4.2.13 on 2024-05-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Repeat_password', models.CharField(max_length=50)),
            ],
        ),
    ]
