# Generated by Django 4.2.13 on 2024-05-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRegistration',
            new_name='Customer_Registration',
        ),
    ]
