# Generated by Django 4.2.13 on 2024-06-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customerregistration_customer_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_registration',
            name='User_Photo',
            field=models.ImageField(default=None, upload_to='User_Images/'),
        ),
    ]
