# Generated by Django 4.2.13 on 2024-06-11 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0014_customer_registration_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Registration',
            new_name='Customer_Profile',
        ),
    ]
