# Generated by Django 4.2.13 on 2024-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_customer_registration_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_profile',
            name='contact_no',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
