# Generated by Django 4.2.13 on 2024-06-11 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='Dish', max_length=50)),
                ('Description', models.CharField(default='A dish is a specific preparation of food that is created by combining various ingredients and cooking them according to a particular recipe or method. Dishes can range from simple to complex and can be served as part of a meal or as a standalone item. They can be hot or cold, sweet or savory, and can come from any cuisine around the world.', max_length=500)),
                ('Name', models.CharField(max_length=70)),
                ('Image', models.ImageField(upload_to='Dish_Images/')),
                ('DishType', models.CharField(choices=[('V', 'veg'), ('NV', 'Nonveg'), ('S', 'Snacks'), ('BF', 'Breakfast')], max_length=30)),
                ('Availability', models.CharField(choices=[('Availaible', 'yes'), ('Not Available', 'no')], max_length=50)),
                ('Price', models.IntegerField(max_length=5)),
                ('Dis_price', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Indian Food Restaurant', max_length=50)),
                ('image', models.ImageField(blank=True, default='defaultuser.jpg', null=True, upload_to='restaurants/')),
                ('location', models.CharField(default='Mumbai', max_length=50)),
                ('cost_for_two', models.DecimalField(decimal_places=2, default=800.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
