# Generated by Django 4.2.13 on 2024-06-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_orderdish_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
