# Generated by Django 4.2.13 on 2024-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_restaurantdish_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdish',
            name='Description',
            field=models.CharField(default='A dish is a specific preparation of food that is created by combining various ingredients and cooking them according to a particular recipe or method. Dishes can range from simple to complex and can be served as part of a meal or as a standalone item. They can be hot or cold, sweet or savory, and can come from any cuisine around the world.', max_length=5000),
        ),
    ]
